### ISSUE TITLE
What does the vis mean in the dump_data.py?

### ISSUE THREAD

**Issue by punisher220** [vcg-uvic/learned-correspondence-release#37]
Excuse me, I read the dump_data.py code and got confused about the vis part(including your visibility folder files).
  
  I am sure that at Line 396 in **dump_data.py** the vis returned from loadFromDir() for a single part(train or test or validation) of a dataset is a **Symmetric matrix M** and the Diagonal elements are all -1. In addition, M(i,j)=M(j,i) when i != j.
  Then you selected those index pairs with values over 100(default setting in config as **data_vis_th_tr** parameter).
  
  I wonder:
  1. Where are the values in the vis_00000x.txt from? Or what does the M(i,j) value mean between the **i** th image and the **j** th image in **images.txt**? 
      I guess they are the number of matching points from SIFT between the 2 images. Is it right?
      If so, did you get the result from VisualSFM? or any other tools?
  2. Why you select the values over 100 to put into pairs? What will happen if the value is relatively low?

**Comment by etrulls** [comment]
You guessed right, it's just a simple co-visibility metric: the number of points in the 3d model in common between images i and j (for i != j). The reconstructions came from visualsfm, yes. And we don't use pairs with fewer than 100 points in common because they probably share very little content and might be harmful for training. This is not something we tuned (at all, IIRC).
