### ISSUE TITLE
Should I re-train the model with specific point extraction method to do the mis-match removal test?

### ISSUE THREAD

**Issue by punisher220** [vcg-uvic/learned-correspondence-release#43]
Excuse me, you provided 2 models which are for SIFT and LIFT.
They are separately trained from prepared data as:(**data_dump.py** did this):
SIFT matching samples from images and LIFT matching samples, is it right?

If I would like to do the image matching test as: SURF Extraction+BFMatch+LFGC(Your repo)

Should I re-train the model with SURF key-points matching samples?
Or just using your SIFT-model directly is also OK?

**Comment by etrulls** [comment]
Since SURF is a handcrafted method inspired by SIFT, it will have similar statistics to it in terms of keypoint/match distributions, so you can try using the model pretrained with SIFT matches first (see table 9 [here](https://arxiv.org/pdf/2003.01587.pdf)), but in general, yes, the network should be retrained.

Note that SURF is severely outperformed by most methods nowadays, so you won't get much ouf of it in any case.
